name: Swift
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Switch to Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Build
        env:
          PROJECT: Enigma.xcodeproj
          SCHEME: Enigma (iOS)
          DESTINATION: platform=iOS Simulator,OS=15.0,name=iPhone 13
        run: |
          xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release clean test CODE_SIGNING_ALLOWED=NO | xcpretty
